<?
$PERM["kabinet-pokupatelya"]["2"]="D";
$PERM["kabinet-pokupatelya"]["3"]="D";
$PERM["kabinet-pokupatelya"]["4"]="D";
$PERM["kabinet-pokupatelya"]["8"]="X";
$PERM["kabinet-pokupatelya"]["7"]="D";
$PERM["kabinet-pokupatelya"]["5"]="D";
$PERM["kabinet-prodavtsa"]["2"]="D";
$PERM["kabinet-prodavtsa"]["3"]="D";
$PERM["kabinet-prodavtsa"]["4"]="D";
$PERM["kabinet-prodavtsa"]["8"]="X";
$PERM["kabinet-prodavtsa"]["6"]="D";
$PERM["kabinet-prodavtsa"]["5"]="D";
$PERM["obyavleniya"]["8"]="X";
$PERM["o-service"]["8"]="X";
$PERM["bitrix"]["8"]="D";
$PERM["video"]["*"]="R";
$PERM["online"]["*"]="R";
$PERM["desktop_app"]["*"]="R";
$PERM["search"]["5"]="W";
$PERM["products"]["5"]="W";
$PERM["services"]["5"]="W";
$PERM["news"]["5"]="W";
$PERM["contacts"]["5"]="W";
$PERM["company"]["5"]="W";
$PERM["index.php"]["5"]="W";
$PERM["/"]["*"]="R";
?>